export { default as Home } from './Home'
export { default as MyPage } from './MyPage'
export { default as Template } from './Template'
export { default as SignupPage } from './SignupPage'
export { default as LoginPage } from './LoginPage'
export { default as LoginkakaPage } from './Loginkakako'
