export { default as Home } from './Home'
export { default as MyPage } from './mypages/MyPage'
export { default as SignupPage } from './SignupPage'
export { default as LoginPage } from './LoginPage'
export { default as TemplatePage } from './TemplatePage'
export { default as AdminPage } from './admin-pages/AdminPage'
